### PR TITLE
History-preserving move from `qiskit-tutorials/algorithms` to `qiskit_algorithms/tutorials`

### PR DESCRIPTION
**Pull request by robotAstray**
### Summary

This PR aims to resolve part of the issue #14, to be specific the first step (i.e. history preserving migration of [`qiskit-tutorials`](https://github.com/Qiskit/qiskit-tutorials) 's   [`./tutorials/algorithms`](https://github.com/Qiskit/qiskit-tutorials/tree/master/tutorials/algorithms) folder).

### Details and comments

- The git history preserving method was used to migrate the content of `qiskit-tutorials\algorithms` into `qiskit-algorithms\docs\tutorials`
- Since the initial repo already had `01_introduction.ipynb` I made sure that the file is included with the previous changes
- Tutorial `09_IQPE.ipynb` was removed since it does not contain any reference to  `qiskit-algorithms`

### CODE REVIEW

**Comment by robotAstray** [comment]
@woodsp-ibm, I might need to fix the last 3-5 commits as they should be one commit with reference to issue #14

**Comment by woodsp-ibm** [comment]
> I might need to fix the last 3-5 commits 

Having one or two extra commits is probably ok, but whatever they are will end up getting kept since we want the coomplete commit history. As far as the 01 tutorial I guess I was expecting to override what was already here so we got the history. Taking the original it would need fixing up again, but the others all need fixing too and it all could be done in a follow up. As I mentioned it was just quickly copied over here so we could have CI up an running with the docs.

**Comment by robotAstray** [comment]
> > I might need to fix the last 3-5 commits
> 
> Having one or two extra commits is probably ok, but whatever they are will end up getting kept since we want the coomplete commit history. As far as the 01 tutorial I guess I was expecting to override what was already here so we got the history. Taking the original it would need fixing up again, but the others all need fixing too and it all could be done in a follow up. As I mentioned it was just quickly copied over here so we could have CI up an running with the docs.

Hello @woodsp-ibm, thank you for your feedback, it is really helpful.

I see now the mistake. Just to confirm, would you like me to leave it as it is for this time?

**Comment by robotAstray** [comment]
I can see the error is `No module named 'qiskit_aer'` I can add
```
qiskit-aer >= 0.12.2
```
in the `requirements.txt`  file if you are happy with that, and I think that should resolve the matter.

**Comment by woodsp-ibm** [comment]
@robotAstray Thanks for giving this a shot though!

**Pull request closed without merging**
