### PR TITLE
Deploy docs to GitHub Pages

### PR DESCRIPTION
**Pull request by arnaucasau**
### Summary

This PR changes the `deploy-docs.yml` workflow to deploy the documentation to GitHub Pages to migrate the project away from the qiskit.org domain.

More information about the change and a quick guide to set up GitHub pages can be found at: https://github.com/Qiskit/ecosystem/issues/578

Reminder task for maintainers here to update the doc link in the About text for the repo on the main page once this change happens and the docs are re-deployed . This will need backporting to stable to have it apply to present docs version before it can be re-run.

- [ ] Update About text doc link

### CODE REVIEW

**Review by ElePT — COMMENTED** [review]
Thanks Arnau for the PR, let's wait for https://github.com/testing-cabal/testtools/pull/371 and see if the CI gets fixed once it's merged.

**Comment by woodsp-ibm** [comment]
Once this is done the first section in the README, about installation, will need its link updating.

**Review by woodsp-ibm — APPROVED** [review]
@arnaucasau I have done a couple of workarounds to avoid the CI failures and as a result this can be moved forwards now. I think it's ready right.

Just as clarification, as I understand it, publishing is a 2 step process now, not just running this workflow. But now once its run the pages deployed to gh-pages need a second manual step to be published?

**Comment by arnaucasau** [comment]
Great, thank you @woodsp-ibm! Regarding your question, I guess when you say publish it, you mean to `qiskit.org`, but correct me if I'm wrong. 

We only need the first of the two steps you mentioned. With this workflow, the docs will be deployed to GitHub Pages where the documentation will live, and once this change is done, I will set up the redirects from `qiskit.org` to the GitHub Pages link we have.

**Comment by woodsp-ibm** [comment]
@arnaucasau I was reading it was "deployed" to a `gh-pages` branch - maybe thats all that there is to it and its live from there and needs no extra step.

**Comment by arnaucasau** [comment]
Oh, I see what you meant now. Exactly, we only need to deploy to the `gh-pages` branch, and the publish step is done automatically by a workflow called `pages-build-deployment`. The only important thing is to set the branch correctly in the settings. Here you can find a short tutorial I wrote: https://github.com/Qiskit/ecosystem/issues/578#issuecomment-1858033321

**Comment by woodsp-ibm** [comment]
@arnaucasau  Ok, I ran the workflow, updated the Settings and the docs are now live https://qiskit-community.github.io/qiskit-algorithms/ I guess a redirect for former ecosystem url can be done now.

**Pull request merged**
