### PR TITLE
Add Python 3.12 support

### PR DESCRIPTION
**Pull request by woodsp-ibm**
### Summary

Given Qiskit 0.45.1 just released with Python 3.12 support I have added that here to Algorithms. 

### Details and comments

I added a new Ubuntu 3.12 run so that OS spans all the versions. I changed Mac and Windows to 3.12 from 3.11 so it tests the min and max versions supported now (just as it did before when 3.11 was the max). I did the same for Qiskit Main monitoring.

FYI I do not have 3.12 locally at present to check things so we'll see how it goes here...

- [ ] This will of course need the branch protection rules changing.

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
This works with Ubuntu and Mac, but not Windows, where the cause is Aer not yet supporting 3.12 In Ubuntu and Mac it manages to  build the wheels from source, so things pass there. Not so in Windows. I think the only dependence here for Aer is just in the tutorials right with the one that shows VQE with simulation under a noise model.

**Comment by woodsp-ibm** [comment]
I put this OnHold for now. We could drop the min level for Win to 3.11 or wait until Aer supports 3.12 and wheels are released.

**Review by ElePT — COMMENTED** [review]
I think that limiting the CI Python version for Win to 3.11 in CI sounds reasonable given the current release timeline of Aer. There is a good amount of interest in Python 3.12 being supported in Qiskit in general and I think it would be nice to start running CI on it on some platforms.

**Comment by woodsp-ibm** [comment]
I updated the main branch rules for the jobs as they now stand from this PR.

**Pull request merged**
