### PR TITLE
Update CI to use latest windows

### PR DESCRIPTION
**Pull request by woodsp-ibm**
### Summary

Changed windows-2019 to windows-latest (current same as windows-2022) so it running on a newer version and use latest like is done on others. My recollection of it using windows-2019 specifically was when Aer was being built from source. As this is no longer the case it seems better to switch to a newer version and do -latest like is done with Ubuntu and Mac

I already did this in Nature https://github.com/qiskit-community/qiskit-nature/pull/1266 as part of updating CI there.

### Details and comments

The branch rules will need updating to account for the job name change.

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
I am guessing the failures are due to the newly released 0.45 Terra. The nightly yesterday ran on the prior version, so I will check what the outcome of tonight's nightly is as I would expect that to fail just as this is now.

**Review by ElePT — APPROVED** [review]
Now that the QDrift fix is merged, LGTM!

**Comment by woodsp-ibm** [comment]
@mergifyio refresh

**Comment by woodsp-ibm** [comment]
I updated the branch rules to drop `windows-2019` jobs from being required and replace by `windows-latest`.

**Pull request merged**
